version: "3.9"
services:
  db:
    image: postgres:16.4
    container_name: postgres_panel_turnos
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: panel_turnos
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d panel_turnos"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
