FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build  # dist/panel-turnos-web

FROM nginx:1.27-alpine
COPY --from=build /app/dist/panel-turnos-web /usr/share/nginx/html
COPY infra/nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
